// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  herocard: dynamic(() => import("./Herocard")),
  landing_site: dynamic(() => import("./LandingSite")),
  sign_up: dynamic(() => import("./SignUp")),
  upload: dynamic(() => import("./Upload")),
};
