// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  doublebox: dynamic(() => import("./Doublebox")),
  hero: dynamic(() => import("./Hero")),
};
